### ISSUE TITLE
Don't add commas to the tree for Arethusa

### ISSUE THREAD

**Issue by LFDM** [perseids-project/perseids_docs#187]
It's good to have the `AuxK`s bound to the `ROOT` already - probably not so much the `AuxX`s probably. Identifying them as such is good, but I would personally prefer them to have a head value of `""`

**Comment by balmas** [comment]
Vanessa says the AuxK's aren't hanging now, which seems odd, but need to verify. Also, she prefers the commas to be hung too...

**Comment by balmas** [comment]
Ah, they aren't being hung because attach to root is off -- poor logic on my part because this *wasn't* connected to the attach to root option and shouldn't have been.

But as Vanessa points out, this is really a personal preference, so we need to make it configurable if we're going to do it.  reverting for now.
