### ISSUE TITLE
Is it possible to see a diff file?

### ISSUE THREAD

**Issue by davidamichelson** [perseids-project/perseids_docs#364]
When a record is an edit of an existing record, is it possible to see a diff file of some kind or even a diff summary? Would the underlying git allow this? Or alternately we could require our users submit to our git first and then we could make a git available.

Thoughts? Including @wsalesky on this one.

**Comment by davidamichelson** [comment]
We see that this seems to be possible in the finalize page:



 --- /dev/null

 +++ b/Syriaca_Data/place/1814.xml

**Comment by balmas** [comment]
As you note, this is currently only exposed in the finalization stage, but I think it would be possible to add it at others.  Where do you want it? In the vote stage?

**Comment by davidamichelson** [comment]
Yes please a diff file would be very useful at the vote stage and good to have diff view as an option at any point like preview view

**Comment by balmas** [comment]
In implementing this, I realize an oversight I made was that we won't have the original version of the file being edited in the local Perseids git repo, as it is used as the editing environment only. I CAN do a diff against the currently live version of the record being edited pretty easily.  Ideally I'd like to just be able to retrieve the version to diff against using the URI of the place record, e.g. "http://syriaca.org/place/1000" but in order to use that, I need the srophe environment to enable CORS. If that's not possible, the alternative would be to retrieve the raw xml directly from the source github repo, which I could do, but requires one or two extra hacks in the code that I'd like to avoid, if CORS can simply be enabled.  

@wsalesky do you think it would be possible to enable CORS on the gazetteer URIs? (I have a feeling others might request this anyway..)

**Comment by balmas** [comment]
@davidamichelson do you want this diff to be available only to reviewers, or to a submitter too?

**Comment by wsalesky** [comment]
I will look into it.

**Comment by wsalesky** [comment]
Okay I have added CORS for the tei version of the data id: "http://syriaca.org/place/1000/tei"  @balmas let me know if you have any trouble with it.

**Comment by balmas** [comment]
works great @wsalesky . thanks!

**Comment by balmas** [comment]
Currently implemented on Voting screen:

![diff](https://cloud.githubusercontent.com/assets/644870/20978025/5840e3aa-bc75-11e6-8e0e-49fbb057942c.png)
