### ISSUE TITLE
Treebank from Edit page somehow fails to load the treebank

### ISSUE THREAD

**Issue by PonteIneptique** [perseids-project/perseids_docs#398]
Context : Firefox 51.0.1 64-Bit (Ubuntu)

Steps : 

1. Create a treebank with the selector (First seneca controversia, book 1 chapter 1 to book 2 chapter 2)
2. Do some editing in Arethusa (You are landing on the URI  http://arethusa.perseids.org/app/#/perseids?doc=45997&s=1&direction=ltr&lang=lat )
3. Save the editing in there
4. Click "Exit to Perseids"
5. Click on the first sentence (Your are now on URI http://www.perseids.org/tools/arethusa/app/#/perseids?chunk=1&doc=45997 )
6. Text fails to load : 

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://sosol.perseids.org/sosol/dmm_api/item/TreebankCite/45997. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘http://www.perseids.org’)
```

I redid it at least once and it loaded, but the bug happened to the person I was demonstrating to at the exact same time...

**Comment by balmas** [comment]
ah that's very interesting. The cors policy should be allowing any subdomain of perseids.org to make the requests but it depends upon what the browser is sending as the Origin, and I'm wondering if there is some caching going on, since arethusa is first accessed from arethusa.perseids.org and then from www.perseids.org in the same browser session.  There isn't any reason to retain that inconsistent behavior so I'm switching sosol to use the newer arethusa.perseids.org url for the links on the sentence list, to match what the client apps input form is using.  Please  let me know if you see the problem recur!

**Comment by balmas** [comment]
closing this because the above-mentioned change is deployed, but feel free to reopen if it occurs again for you.
