### ISSUE TITLE
Split values in "Your Vote" dropdown

### ISSUE THREAD

**Issue by nathangibson** [perseids-project/perseids_docs#407]
I can't manage to get a screenshot, but on the "Votes" page under "Your Vote (Required)" the options are 

- Accept
- Return
- to 
- Revise 
(instead of "Return to Revise")

**Comment by balmas** [comment]
ah, okay I'll fix that tonight!

**Comment by nathangibson** [comment]
Thanks!

**Comment by balmas** [comment]
Ah this is interesting, this is actually by design. You can specify multiple values to show in the vote drop down for a decree, by separating them by spaces. I'm not sure why you would want to do that actually, but it seems that we need one word (or CamelCase words) in the vote drop down.  So, ReturnToRevise instead of Return to Revise.  Is that liveable? @nathangibson

**Comment by nathangibson** [comment]
Sounds good to me!
Nathan P. Gibson, Ph.D.
nathanpgibson@gmail.com <mailto:nathanpgibson@gmail.com>
https://vanderbilt.academia.edu/NathanGibson <https://vanderbilt.academia.edu/NathanGibson>

Postdoctoral Scholar in Syriac Studies and Digital Humanities
Vanderbilt University & Syriaca.org <http://syriaca.org/>
nathan.p.gibson@vanderbilt.edu <mailto:nathan.p.gibson@vanderbilt.edu>

Gastwissenschaftler
Institut für den Nahen und Mittleren Osten
Ludwig-Maximilians-Universität München
Nathan.Gibson@lmu.de <mailto:Nathan.Gibson@lmu.de>

**Comment by balmas** [comment]
ok. I've updated all the boards to use camel case on ReturnToRevise

**Comment by nathangibson** [comment]
Thanks!
