### ISSUE TITLE
Voting assignment

### ISSUE THREAD

**Issue by nathangibson** [perseids-project/perseids_docs#410]
@balmas -- 3rd workflow/interface suggestion:

If a community has a set number of assignable voters, that means we have to assign a voter for each of the 3 boards a record goes through. If the number of voters is set to 0, it skips this step and people can vote immediately, but it is then not possible to assign it to a specific person on any of the boards, right?

Having to choose a voter plus vote on each of the 3 boards is quite cumbersome. But on the second board it is important to be able to assign subject experts in some situations. 

How hard would it be to either
1) Assign number of voters at the board rather than community level. OR
2) Allow optional voter assignment when number of voters is set to 0.

**Comment by balmas** [comment]
option 2 is much easier than option 1

**Comment by nathangibson** [comment]
Then I guess we want option 2 :-). Thanks.

**Comment by balmas** [comment]
it turns out that option 1 is better from the perspective of the code, so I am working on that -- assignment options will be set on the board level and not the community, and you will be able to set a max # of voter assignments as well as a flag to indicate whether or not assignment is required for a board.  The latter will be what determines whether unassigned board members can see all publications or just those they are assigned to.

**Comment by nathangibson** [comment]
This sounds excellent. Thanks!
